#!/usr/bin/env python3
"""Pre-registered forward test: does fading a large model-vs-market gap win?

REGISTERED 2026-08-29. Every parameter below is FROZEN. Nothing here is fitted
at run time, nothing is re-tuned as rows arrive, and only slates STRICTLY AFTER
the registration date are scored. That is the entire value of this module: the
hypothesis was generated by searching the ledger, so the only test it cannot
contaminate is one whose rule was fixed before the data existed.

WHY IT EXISTS. Backing the model's largest model-vs-market gaps loses
monotonically (value_probe.py section 2). The mirror hypothesis -- that the
delta is a real over/under-valuation signal with its sign flipped, so fading it
should win -- looked strong on a walk-forward search: +20.2% ROI at gap > 0.10,
and an inversion slope whose CI excluded zero.

WHY THAT WAS WRONG, recorded here so it is not rediscovered. The search
recomputed the model probability each slate from a logit fitted on prior slates
only. Early slates fit on 75-102 rows produced slopes of +8.5 to +9.8 against a
stable full-sample +5.78, which inflates |gap| on exactly those slates -- so
"gap > 0.10" selected unsettled fits, not genuine disagreement (69% of that set
was fitted on <200 rows, against a 20% base rate). All five underdog wins that
carried the result landed on three consecutive slates, 2026-07-08/09/10, all in
that unsettled region. Holding the coefficients FIXED, as this module does, the
effect inverts: every threshold is negative in the discovery sample.

    threshold   discovery ROI (frozen coefficients, n=718)
    gap > 0.00    -5.7%
    gap > 0.02    -1.8%
    gap > 0.04    -0.1%
    gap > 0.06    -4.2%   <- PRIMARY
    gap > 0.10    -7.8%

SO THE REGISTERED PRIOR IS NEGATIVE. This module is not tracking a promising
rule; it is holding a dead one still so that a future hot streak cannot be read
as a discovery. If it turns positive, that is a hypothesis worth a fresh look,
NOT a green light -- see the gate below.

WHAT IT CANNOT DO.
  * It cannot make the discovery sample count. Rows on or before the
    registration date are excluded by construction, and re-including them to
    "get more power" would destroy the only property this module has.
  * It cannot reach a verdict soon. At the primary threshold the rule fires on
    ~1.6 of 15 games a slate, and separating a +5% ROI edge from zero needs
    ~1,300 bets: several seasons. The gate is stated rather than hidden so
    nobody reads 40 bets as a result.
  * It cannot tell you the model is bad. It tests one derived betting rule, not
    the model's predictive value, which is real and separately measured
    (xw_net alone predicts winners at z = +2.71).

    python forward_test.py
"""
import os

import numpy as np
import pandas as pd

# ---------------------------------------------------------------------------
# FROZEN REGISTRATION BLOCK. Changing any value below invalidates the test and
# restarts it from zero: the numbers are only meaningful because they were
# fixed before the scored rows existed. test_forward_test_registration_frozen
# pins every one of them, so editing one means deliberately editing a test that
# says not to -- which is the point.
# ---------------------------------------------------------------------------
REGISTERED_ON = "2026-08-29"      # slates STRICTLY after this date are scored
# logit(p_home) = A + B * xw_net, fitted once on the 718 graded rows carrying a
# lean, a delta and a close as of the registration date. Never refitted.
COEF_A = 0.1292658378
COEF_B = 5.7751338037
GAP_THRESHOLD = 0.06              # primary; the others are reported as secondary
DIRECTION = "fade"                # bet AGAINST the model's lean
STAKE = 1.0                       # flat
SECONDARY_THRESHOLDS = (0.00, 0.02, 0.04, 0.06, 0.10)
# Bets needed to separate a +5% ROI from zero at |z| = 2, given the observed
# per-bet sd of ~0.91. Stated so a hot 40-bet stretch cannot read as a verdict.
GATE_BETS = 1300

LEDGER = os.path.join("data", "mlb_lean_ledger.csv")


def _payout(ml):
    ml = np.asarray(ml, dtype=float)
    return np.where(ml > 0, ml / 100.0, 100.0 / np.abs(ml))


def scored_rows(led=None):
    """Graded rows AFTER the registration date, with the frozen gap attached."""
    if led is None:
        if not os.path.exists(LEDGER):
            return None
        led = pd.read_csv(LEDGER, low_memory=False)
    need = ["status", "game_date", "close_p_home", "xw_lean", "xw_net", "home",
            "full_home", "full_away", "close_home_ml", "close_away_ml"]
    if any(c not in getattr(led, "columns", ()) for c in need):
        return None
    g = led[(led["status"] == "graded") & led["close_p_home"].notna()
            & led["xw_lean"].notna() & led["xw_net"].notna()].copy()
    # Strictly after: the registration date itself already held graded rows, so
    # `>=` would silently readmit part of the discovery sample.
    g = g[g["game_date"].astype(str) > REGISTERED_ON]
    if g.empty:
        return g
    g["lean_home"] = g["xw_lean"] == g["home"]
    home_won = g["full_home"] > g["full_away"]
    g["lean_won"] = np.where(g["lean_home"], home_won, ~home_won)
    g["p_lean"] = np.where(g["lean_home"], g["close_p_home"], 1 - g["close_p_home"])
    # The side this rule actually backs, and its price.
    g["p_bet"] = 1 - g["p_lean"]
    g["ml_bet"] = np.where(g["lean_home"], g["close_away_ml"], g["close_home_ml"])
    g["bet_won"] = ~g["lean_won"].astype(bool)
    ph = 1.0 / (1.0 + np.exp(-(COEF_A + COEF_B * g["xw_net"].values)))
    model_p = np.where(g["lean_home"], ph, 1 - ph)
    g["gap"] = model_p - g["p_lean"]
    g["profit"] = np.where(g["bet_won"], STAKE * _payout(g["ml_bet"]), -STAKE)
    return g


def _line(f, label):
    n = len(f)
    if not n:
        return f"    {label:<14}    no qualifying bets yet"
    w = int(f["bet_won"].sum())
    u = float(f["profit"].sum())
    # Poisson-binomial: p_i are the market's, not estimated from the outcomes.
    se = float(np.sqrt(np.sum(f["p_bet"] * (1 - f["p_bet"]))) / n)
    z = (f["bet_won"].mean() - f["p_bet"].mean()) / se if se > 0 else float("nan")
    return (f"    {label:<14}  n={n:<4d} {w}-{n - w}  {u:+7.2f}u  "
            f"ROI {u / n * 100:+6.1f}%   vs price z={z:+.2f}")


def report_lines(led=None):
    """Report body as a list of lines. Pure -- no printing, no file writes."""
    out = ["pre-registered forward test  (registered "
           f"{REGISTERED_ON}; {DIRECTION} the lean when gap > {GAP_THRESHOLD:.2f})"]
    g = scored_rows(led)
    if g is None:
        out.append("    ledger unavailable or missing columns -- not scored")
        return out
    slates = g["game_date"].nunique() if len(g) else 0
    out.append(f"    eligible rows since registration: {len(g)} over {slates} slates")
    if not len(g):
        out.append("    nothing to score yet. Discovery-sample prior is NEGATIVE "
                   f"({-4.2:+.1f}% at the primary threshold) -- this tracks a "
                   "hypothesis already argued dead.")
        return out
    out.append(_line(g[g["gap"] > GAP_THRESHOLD], "PRIMARY"))
    for thr in SECONDARY_THRESHOLDS:
        if abs(thr - GAP_THRESHOLD) < 1e-9:
            continue
        out.append(_line(g[g["gap"] > thr], f"secondary >{thr:.2f}"))
    n_primary = int((g["gap"] > GAP_THRESHOLD).sum())
    out.append(f"    GATE: {n_primary} of ~{GATE_BETS} bets needed to separate a "
               f"+5% ROI from zero. Read nothing before then.")
    out.append("    Prior is NEGATIVE by construction (see forward_test.py); a "
               "positive run here is a hypothesis, not a result.")
    return out


if __name__ == "__main__":
    print("\n".join(report_lines()))
